apiVersion: apps/v1
kind: Deployment
metadata:
  name: josubartolome_cp2
  labels:
    app: josubartolome_cp2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: josubartolome_cp2
  template:
    metadata:
      labels:
        app: josubartolome_cp2
    spec:
      containers:
      - name: josubartolome_cp2
        image: acrcasopractico.azurecr.io/josubartolome_cp2:casopractico2
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/data"
          name: almacenamiento
      volumes:
      - name: almacenamiento
        persistentVolumeClaim:
          claimName: pvc-datos
