apiVersion: apps/v1
kind: Deployment
metadata:
  name: josu-cp2-despliegue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: josu-cp2-app
  template:
    metadata:
      labels:
        app: josu-cp2-app
    spec:
      containers:
      - name: josu-cp2-container
        image: acrcasopractico.azurecr.io/josubartolome_cp2:casopractico2
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/data"
          name: almacenamiento
      volumes:
      - name: almacenamiento
        persistentVolumeClaim:
          claimName: pvc-datos
